- src/graph/nodes.py
- web/src/app/settings/tabs/about.md
Refering to https://github.com/bytedance/deer-flow/issues/12, a necessary termination log is added for no tool calls situation in coordinator node.
> feat: add necessary log when no tool calls

- README.md
- README_ja.md
- README_zh.md
> docs: add ja readme

- web/src/app/chat/page.tsx
next/dynamic is a composite of [React.lazy()](https://react.dev/reference/react/lazy) and [Suspense](https://react.dev/reference/react/Suspense).
Using loading argument instead of Suspense component fallback prop.
The doc is here: https://nextjs.org/docs/pages/guides/lazy-loading#nextdynamic
> feat: adjust Suspense loading

- web/.env.example
- web/src/app/chat/components/site-header.tsx
- web/src/app/page.tsx
- web/src/env.js
show this project  star count in the site header.
> feat: show repo star on site-header

- web/src/app/chat/components/message-list-view.tsx
- web/src/app/chat/components/messages-block.tsx
- web/src/core/store/store.ts
* Prevent the message component from being unmounted repeatedly
* Add `useShallow` for complex store selector
* Fix #21
> pref: message render performence

- src/prompts/researcher.md
Polish the researcher prompt to stess the time range usage while invoking web search tool. cc: @MagicCube
> refactor: stess the time range while using web search tools

- web/src/app/chat/main.tsx
> fix: update responsive design calculations for chat layout

- .env.example
- src/graph/nodes.py
#55 
This PR can resolve the issue of exceeding the default tool invocation limit by setting the recursion limit through an environment variable.mit
> Fix :This PR can resolve the issue of exceeding the default tool invocation limit by setting the recursion limit through an environment variable.mit

- src/llms/llm.py
- tests/integration/test_nodes.py
add unit test for background node
> test: add background node unit test

- src/config/configuration.py
- src/config/report_style.py
- src/graph/nodes.py
- src/prompts/reporter.md
- src/server/app.py
- src/server/chat_request.py
- tests/integration/test_template.py
- web/src/app/chat/components/input-box.tsx
- web/src/app/settings/tabs/general-tab.tsx
- web/src/components/deer-flow/icons/report-style.tsx
- web/src/components/deer-flow/report-style-dialog.tsx
- web/src/core/api/chat.ts
- web/src/core/store/settings-store.ts
- web/src/core/store/store.ts
> feat: support to adjust writing style

- src/config/loader.py
- tests/test_state.py
- tests/unit/config/test_configuration.py
- tests/unit/config/test_loader.py
Added some unit test to increase the code coverage of configuration.
> test:unit tests for configuration

- src/config/agents.py
- src/prompt_enhancer/__init__.py
- src/prompt_enhancer/graph/builder.py
- src/prompt_enhancer/graph/enhancer_node.py
- src/prompt_enhancer/graph/state.py
- src/prompts/prompt_enhancer/prompt_enhancer.md
- src/server/app.py
- src/server/chat_request.py
- tests/unit/prompt_enhancer/__init__.py
- tests/unit/prompt_enhancer/graph/__init__.py
- tests/unit/prompt_enhancer/graph/test_builder.py
- tests/unit/prompt_enhancer/graph/test_enhancer_node.py
- tests/unit/prompt_enhancer/graph/test_state.py
- web/src/app/chat/components/input-box.tsx
- web/src/components/deer-flow/icons/enhance.tsx
- web/src/components/deer-flow/message-input.tsx
- web/src/components/magicui/border-beam.tsx
- web/src/core/api/index.ts
- web/src/core/api/prompt-enhancer.ts
> feat: implement enhance prompt

- src/graph/nodes.py
- src/graph/types.py
- src/server/app.py
- tests/integration/test_nodes.py
refactor background check logic to support multi-round dialogue
> refactor: refine the background check logic

- web/src/core/api/chat.ts
add try catch for the `chatStream` method.
> chore: append try catch

- src/server/app.py
- src/tools/tts.py
- tests/integration/test_tts.py
- tests/unit/server/test_app.py
- tests/unit/server/test_chat_request.py
- tests/unit/server/test_mcp_request.py
- tests/unit/server/test_mcp_utils.py
This pull request introduces several updates, including dependency additions, code refactoring, and extensive unit test coverage for new and existing functionality. The changes focus on improving error handling, adding tests for server request and utility modules, and refining logging and return values for better clarity.
* Added `pytest-asyncio>=1.0.0` to the `dev` dependencies in `pyproject.toml` to support asynchronous test cases.
* Refactored the `text_to_speech` endpoint in `src/server/app.py` to streamline exception handling and improve readability. Removed redundant `try` block nesting and adjusted error messages for missing environment variables. [[1]](diffhunk://#diff-f5582720a2c21fe3f110577d491f104e06109eea939c2336dbf8ae7fbf60d6a7L195-R204) …
> test: add unit tests of the app

- conf.yaml.example
- docs/configuration_guide.md
- src/tools/search.py
This PR adds the ability to control search domains for the Tavily search engine through the configuration file (`conf.yaml`). It implements two key features:
- `include_domains`: A whitelist of domains to restrict search results to specific trusted sites
- `exclude_domains`: A blacklist of domains to filter out unwanted sources
When using Tavily as a search engine, results may include irrelevant or unreliable information from a wide range of websites. This can lead to hallucinations or poor quality data being returned to the agent, affecting the overall performance and reliability of the system.
The solution allows users to:
1. Specify a list of trusted domains to prioritize in searches (whitelist)
2. Specify domains to exclude from search results (blacklist)
3. Configure these settings …
> feat: add Domain Control Features for Tavily Search Engine

- src/config/__init__.py
- src/crawler/crawler.py
- src/llms/llm.py
- src/prompt_enhancer/graph/enhancer_node.py
- src/rag/vikingdb_knowledge_base.py
- src/tools/search.py
- tests/integration/test_nodes.py
- tests/test_state.py
- tests/unit/config/test_configuration.py
- tests/unit/config/test_loader.py
- tests/unit/crawler/test_article.py
- tests/unit/crawler/test_crawler_class.py
- tests/unit/llms/test_llm.py
- tests/unit/prompt_enhancer/graph/test_builder.py
- tests/unit/prompt_enhancer/graph/test_state.py
- tests/unit/rag/test_ragflow.py
- tests/unit/rag/test_vikingdb_knowledge_base.py
- tests/unit/server/test_app.py
- tests/unit/server/test_chat_request.py
- tests/unit/tools/test_crawl.py
- tests/unit/tools/test_decorators.py
- tests/unit/tools/test_python_repl.py
- tests/unit/tools/test_search.py
- tests/unit/tools/test_tavily_search_api_wrapper.py
- tests/unit/tools/test_tavily_search_results_with_images.py
- tests/unit/tools/test_tools_retriever.py
- tests/unit/utils/test_json_utils.py
This pull request includes various changes across multiple files, primarily focusing on code cleanup, refactoring, and minor updates to improve maintainability and readability. The most significant changes include the removal of unused imports, updates to type-checking logic, and adjustments to test configurations and fixtures.
* Removed unused imports across multiple files, including `src/crawler/crawler.py`, `src/llms/llm.py`, and several test files, to improve code maintainability and reduce clutter. [[1]](diffhunk://#diff-caec1ea43288002a4036a6bd170e1355a7e9e2c4d3a906bf0dbc5f37cd33c8f2L4) [[2]](diffhunk://#diff-9bc7f752e60bc8722c0d1f1f18c7c4a6ac0e7c0845c5f67cc85ec5c2bdcaeb8aL7) [[3]](diffhunk://#diff-096b29f2231bcefc77c51b85528c06547dc163e3c2fee344006ee05b06746b31L4) …
> fix: fix the lint check errors of the main branch

- src/graph/nodes.py
"/Users/zhangyuehua/Documents/code/deer-flow/src/graph/nodes.py", line 137, in planner_node
if curr_plan.get("has_enough_context"):
^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
> fix:planner AttributeError 'list' object has no attribute 'get'

- pyproject.toml
- src/rag/vikingdb_knowledge_base.py
- tests/unit/rag/test_vikingdb_knowledge_base.py
- uv.lock
solve this issue: https://github.com/bytedance/deer-flow/issues/418
移除volcengine包，先自己实现签名逻辑，后续会将VikingDB SDK迁移到火山SDK V2
> remove volcengine package

- .env.example
- README.md
- src/rag/ragflow.py
- tests/unit/rag/test_ragflow.py
* **Feature**: Implements cross-language search for `RAGFlowProvider`. It works by reading a comma-separated list of languages from the `RAGFLOW_CROSS_LANGUAGES` environment variable. The `.env.example` has been updated with instructions and language options according to RAGFlow UI.
* **Testing**: Added a unit test for the new feature.
> Feat: Cross-Language Search for RAGFlow

- pyproject.toml
- src/config/tools.py
- src/tools/search.py
- uv.lock
Useful for retrieving reliable reference material.
> Feat: Add Wikipedia search engine

- src/graph/nodes.py
- tests/integration/test_nodes.py
Fix #495, to support newer versions of langchain-mcp-adapters
> fix: langchain-mcp-adapters version conflict

- src/tools/tavily_search/tavily_search_results_with_images.py
> fix: update TavilySearchWithImages to inherit from TavilySearchResults

- Dockerfile
- README.md
Fix Issue https://github.com/bytedance/deer-flow/issues/557
> Add psycopg dependencies instruction for checkpointing

- .vscode/launch.json
Debug deerflow server, web with vscode
> Debug deerflow server, web with vscode
