bytedance/deer-flow

web/src/app/chat/components/research-block.tsx
web/src/core/store/store.ts

When the question is simple enough to answer directly, the research team(using DeepSeek V3) will specify the reporter as the only assignee. In this case, the web UI will not render.
This PR has fixed this issue.

fix: allow the first activity to be reporting

---

.env.example
src/graph/nodes.py
src/tools/search.py

Resolve issue #34 : Allow background investigators to utilize the search engine within the environment instead of defaulting to Tavily

fix: background investigator node support more search engine

---

src/tools/search.py

fix the issue #109  Now, if the search engine is set to tavlily, the TAVILY_API_KEY environment variable is allowed to be empty.

fix: fix start error when search engine is not tavliy 

---

Dockerfile

It's better to reduce the backend docker image's size. I found that the current backend docker image size is so large.
This is the current docker base image and the resulting image size after the build process.
| Repository | Tag | Image ID | Created | Size |
|------------|-----|----------|---------|------|
| ghcr.io/astral-sh/uv | python3.12-bookworm | aa0a0983c68f | 6 days ago | 1.06GB |
| deer-flow-backend | latest | 4b3ca7e4cee0 | 40 minutes ago | 1.36GB |
Changing the base image significantly reduced the resulting Docker image size, cutting it by at least 60%.
| Repository | Tag | Image ID | Created | Size |
|------------|-----|----------|---------|------|
| ghcr.io/astral-sh/uv | python3.12-bookworm-slim | 481b72cdf2df | 6 days ago | 165MB |
| deer-flow-backend | latest-slim | …

optimize docker backend image size(reduced by 60%)

---

bootstrap.bat
bootstrap.sh

When I run `bootstrap.sh` without the `-d` option, surprisingly, only `server.py` is running — the frontend sub-project `web` is not started. Therefore, I recommend optimizing the script, as detailed in the diff.

Allow concurrently run server.py and web in production mode.

---

web/src/core/api/chat.ts

原有的分词逻辑在 web/src/core/api/chat.ts 的 fetchReplayTitle() 内判断类型时，有时会因为多了个‘\r’回车符而分词失败，最终导致无法replay
统一替换掉'\r'符号，使replay功能正常

fix: normalize line endings for consistent chunk splitting

---

docs/configuration_guide.md

This PR fixes a typo in the API key placeholder within the configuration guide. The incorrect placeholder YOU_API_KEY has been corrected to YOUR_API_KEY to ensure clarity and accuracy in the documentation.
Changes:
- Updated YOU_API_KEY to YOUR_API_KEY in docs/configuration_guide.md (line 52).
- This small but important correction helps avoid confusion for users when configuring their API keys.

fix: correct placeholder for API key in configuration guide

---

src/graph/nodes.py

The `planner` node expects an llm response in a specific json format, but the llm response does not always comply with that format so pydantic raises a model validation error, as reported by users in these issues:
https://github.com/bytedance/deer-flow/issues/151
https://github.com/bytedance/deer-flow/issues/189
https://github.com/bytedance/deer-flow/issues/191
and possibly here:
https://github.com/bytedance/deer-flow/issues/99
https://github.com/bytedance/deer-flow/issues/217
The fixed code modifies the request made by the `planner` node to force the llm response to strictly comply with the pydantic `Plan` model at the sampler level, so this fix works for any model where the sampler respects a strict json response format parameter.

fix: solves the malformed json output and pydantic validation error

---

web/src/app/settings/tabs/about-tab.tsx
web/src/app/settings/tabs/general-tab.tsx
web/src/app/settings/tabs/index.tsx
web/src/app/settings/tabs/mcp-tab.tsx

right display.
error display on volcengine vefaas.
fixed: after `pnpm run build`, the "General" name was retained.

fix(web): priority displayName for settings name error

---

tests/unit/utils/test_json_utils.py

This pull request adds a comprehensive set of unit tests for the `repair_json_output` function in the `tests/unit/utils/test_json_utils.py` file. These tests cover various scenarios to ensure the robustness and correctness of the function when handling different types of JSON and non-JSON inputs.
* **Basic JSON Handling**:
- Added tests for valid JSON objects and arrays to verify correct parsing and output formatting.
* **Code Block Handling**:
- Added tests for JSON wrapped in code blocks (e.g., ```json and ```ts) to ensure proper extraction and parsing.
* **Malformed and Broken JSON**:
- Added tests for repairing malformed JSON and handling completely unparseable JSON gracefully.
* **Edge Cases**:
- Added tests for edge cases such as empty strings, whitespace-only inputs, and JSON with …

test: add test of json_utils

---

pyproject.toml
src/graph/nodes.py
tests/integration/test_nodes.py
tests/unit/graph/test_builder.py
uv.lock

This pull request introduces several changes, including dependency updates, logic adjustments, and test suite modifications. The most notable updates are the addition of a new dependency, a change in iteration logic for a specific function, and the replacement of an outdated test file with a new one. Below is a categorized summary of the key changes:
* Added `pytest-asyncio>=1.0.0` to the test dependencies in `pyproject.toml` to support asynchronous testing.
* Modified the `human_feedback_node` function in `src/graph/nodes.py` to check if `plan_iterations > 1` instead of `plan_iterations > 0`, aligning the logic with the increment behavior of `plan_iterations`.
* Removed the outdated integration test file `tests/integration/test_nodes.py`, which included extensive mocked fixtures and …

test: add unit tests for graph 

---

web/src/core/utils/json.ts

Avoid JSON parse error "parsed json with extra tokens"
previously，js fence was replace before json fence, so when there is the text like
````
```json
{
...
````
it will become
````
on
{
...
````
and yield an error "parsed json with extra tokens" from parse function
The solution is to change the order of replace functions.

fix: "parsed json with extra tokens" replace json before js fence

---

web/messages/en.json

Fixed a `MISSING_MESSAGE` error that was occurring on the chat page due to missing translation keys for `chat.page` in the internationalization messages.
**Error Details：**
Error: MISSING_MESSAGE: Could not resolve chat.page in messages for locale en.

fix: add missing translation for chat.page

---

web/messages/en.json

Fix missing translation key ```chat.page```
Error Detail

fix: missing i18n message

---

src/graph/nodes.py

When chatting casually, the coordinator does not remember its own outputs, resulting in an abnormal user experience.

fix: fix the memory of coordinator's messages.

---

main.py

Issue:
When running with Console UI, if the user input is empty, an error will be reported directly after pressing Enter and the system will be forced to exit.
Solution:
If the user input is empty, ignore the input and ask the user to input again.

fix:The console UI directly throws an error when user input is empty

---

src/graph/nodes.py

Fix the bug that deep-thinking feature doesn't work, and the bug was introduced by coordinator messages update PR.
We should not add an assistant message if the content is empty, if we add an empty assistant message, the reasoning model won't output reasoning content appropriately.

fix: fix the bug introduced by coordinator messages update

---

.env.example
docs/mcp_integrations.md
src/server/app.py
tests/unit/server/test_app.py

This pull request introduces a new feature for enabling and managing MCP server configurations, along with corresponding updates to the server logic, environment configuration, documentation, and unit tests. The changes ensure that MCP features are disabled by default and can only be activated in a secure environment by explicitly setting an environment variable.
* Added a new environment variable `ENABLE_MCP_SERVER_CONFIGURATION` to control whether MCP server features are enabled. Default is set to `false` in `.env.example`.
* Updated the `chat_stream` and `mcp_server_metadata` endpoints in `src/server/app.py` to validate the status of `ENABLE_MCP_SERVER_CONFIGURATION`. Requests with MCP settings are rejected with a `403 Forbidden` error if the feature is disabled. …

feat: polish the mcp-server configure feature

---

src/config/configuration.py
src/server/app.py
src/workflow.py
tests/unit/config/test_configuration.py

fix this issue.
GraphRecursionError('Recursion limit of 25 reached without hitting a stop condition. You can increase the limit by setting the `recursion_limit` config key.\nFor troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/GRAPH_RECURSION_LIMIT')

fix:env AGENT_RECURSION_LIMIT not work

---

src/prompts/coordinator.md

To issue #432
Refine the coordinator prompt, fix the issue where the coordinator fails to call the handoff_to_planner tool, and support adjustments through replies after the plan is generated. 
Screenshot：

refactor: refine coordinator prompt for Human In The Loop

---

.github/workflows/container.yaml
.github/workflows/lint.yaml

This pull request updates the versions of several GitHub Actions used in workflow configuration files by pinning them to specific commit SHAs, ensuring more reliable and predictable builds. The main changes are focused on the container and lint workflows.
**Workflow dependency updates:**
* **Container workflow**:
- Updated `docker/login-action` to use commit SHA for version `v3.4.0` (`.github/workflows/container.yaml`).
- Updated `docker/metadata-action` to use commit SHA for version `v5.7.0` (`.github/workflows/container.yaml`).
- Updated `docker/build-push-action` to use commit SHA for version `v6.18.0` (`.github/workflows/container.yaml`).
* **Lint workflow**:
- Updated `astral-sh/setup-uv` to use commit SHA for version `v6.5.0` (`.github/workflows/lint.yaml`).

fix: using commit hash as the action version

---

docs/mcp_integrations.md
src/graph/nodes.py
src/server/app.py
src/server/mcp_request.py
src/server/mcp_utils.py
tests/unit/server/test_mcp_utils.py
web/src/core/mcp/types.ts
web/src/core/store/settings-store.ts

In the `langchain_mcp_adapters` library, `_create_streamable_http_session` and `_create_stdio_session` do not have env parameters
However, in the configuration of the MCP server obtained in `_setup_and_execute_agent_step`, the env parameter is carried regardless of whether it is SSE or HTTP.
So when running, this error will appear：
```
File "/Users/anoyer/Desktop/ai_agent/deer-flow/src/server/app.py", line 349, in _astream_workflow_generator
async for event in _stream_graph_events(
File "/Users/anoyer/Desktop/ai_agent/deer-flow/src/server/app.py", line 242, in _stream_graph_events
async for agent, _, event_data in graph_instance.astream(
File "/Users/anoyer/Desktop/ai_agent/deer-flow/.venv/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 2759, in astream
async for _ in …
```

fix: env parameters exception when configuring SSE or HTTP MCP server

---

.env.example

- Changes 'ongodb' to 'mongodb' in LANGGRAPH_CHECKPOINT_DB_URL example.
- This ensures the example configuration is valid and can be used directly.

fix: correct typo in MongoDB connection string within .env.example

---

src/server/mcp_utils.py

fix #562 
This pull request updates the way context values are unpacked in the `_get_tools_from_client_session` function to improve safety and clarity. Instead of unpacking the context manager's result into named variables directly, it now accesses elements by index, which avoids potential issues if the context manager returns more than three values.
Code safety and clarity improvement:
* Changed unpacking in `src/server/mcp_utils.py` (`_get_tools_from_client_session`) to access context manager results by index, ensuring only the required values (`read` and `write`) are used and ignoring any extras.

fix: the stdio and sse mcp server loading issue

---

README.md
README_zh.md

- allow external connections by changing the host to 0.0.0.0.
- security warning to remind users to secure their environment before exposing the service.

docs: add deployment note for Linux servers

---

docs/configuration_guide.md
src/tools/search.py
tests/unit/tools/test_search.py

支持通过配置文件来配置 tavily 搜索工具的返回结果，解决返回结果中图片过多超 token 问题。https://github.com/bytedance/deer-flow/issues/583
tavily官方接口文档：https://docs.tavily.com/documentation/api-reference/endpoint/search
在`conf.yaml`文件中可配置相关参数，各参数具体含义如下：
```yaml
SEARCH_ENGINE:
engine: tavily
include_domains:
- trusted-news.com
- gov.org
- reliable-source.edu
exclude_domains:
- unreliable-site.com
- spam-domain.net
include_images: false
include_image_descriptions: false
include_raw_content: false
```

feat:support config tavily search results

---

src/config/report_style.py
src/prompts/reporter.md
src/rag/__init__.py
src/rag/builder.py
src/rag/moi.py
src/server/app.py
src/tools/search.py
web/messages/en.json
web/messages/zh.json
web/src/app/settings/tabs/general-tab.tsx
web/src/components/deer-flow/report-style-dialog.tsx
web/src/core/api/chat.ts
web/src/core/store/settings-store.ts

This pull request introduces a new, institutional-grade "Strategic Investment" report style. This feature is designed to generate deep, comprehensive analysis for strategic investment institutions, providing actionable insights and in-depth technical assessments.
**Key Changes:**
*   **New Report Style:**
*   Added `strategic_investment` to the `ReportStyle` enum and integrated it throughout the backend and frontend.
*   **Advanced Prompt Engineering:**
*   Developed highly detailed prompts for the reporter agent in both English and Chinese (`src/prompts/reporter.md`).
*   The new prompts instruct the AI to act as a senior investment partner or CTO, with strict requirements for report length (10,000-15,000 words), technical depth, and actionable investment recommendations.
*   A …

feat: add strategic_investment report style

---

README.md
conf.yaml.example
docs/configuration_guide.md
src/prompts/planner.md
src/prompts/planner_model.py

Local models like qwen3:14b fail with Pydantic validation errors when they don't output the `thought` field in their JSON response.
- Made `thought` field optional in Plan model with default value `""`
- Added Ollama configuration example to conf.yaml.example
- Updated documentation to include local model support
- Improved planner prompt with better JSON format requirements
- Verified Pydantic validation works with missing thought field
- Tested with local Ollama models
- All existing functionality preserved
- `src/prompts/planner_model.py` - Made thought field optional
- `src/prompts/planner.md` - Improved JSON format requirements
- `conf.yaml.example` - Added Ollama configuration
- `docs/configuration_guide.md` - Added local model support
- `README.md` - Added local development note

fix: support local models by making thought field optional in Plan model
